Add downstream tests to CI

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -73,9 +73,13 @@ jobs:
     runs-on: "${{ matrix.on }}"
     strategy:
       matrix:
-        environment: ["cppyy-dev-conda-forge", "cppyy-dev-pypi"]
-        task: ["install-cppyy-from-patched", "install-cppyy-from-upstream"]
+        environment: ["cppyy-dev-conda-forge", "cppyy-dev-pypi", "cppyy-pypi", "cppyy-conda-forge"]
         on: ["ubuntu-24.04", "macos-13", "macos-14"]
+        include:
+          - environment: cppyy-dev-conda-forge
+            installation: install-cppyy-from-patched
+          - environment: cppyy-dev-pypi
+            installation: install-cppyy-from-patched
     steps:
     - uses: actions/checkout@v5
       with:
@@ -86,21 +90,43 @@ jobs:
         environments: ${{ matrix.environment }}
         activate-environment: true
     - name: Run install task
-      run: VERBOSE=1 pixi run ${{ matrix.task }}
-    # TODO: Run tests here
-  cppyy-binary:
-    runs-on: "${{ matrix.on }}"
-    strategy:
-      matrix:
-        environment: ["cppyy-pypi", "cppyy-conda-forge"]
-        on: ["ubuntu-24.04", "macos-13", "macos-14"]
-    steps:
-    - uses: actions/checkout@v5
-      with:
-        submodules: recursive
-    - uses: prefix-dev/setup-pixi@v0.9.3
-      with:
-        pixi-version: v0.59.0
-        environments: ${{ matrix.environment }}
-        activate-environment: true
-    # TODO: Run tests here
+      run: VERBOSE=1 pixi run ${{ matrix.installation }}
+      if: ${{ matrix.installation }}
+    - name: Run cppyy test suite
+      # Currently, test fails for a variety of reasons on all builds of cppyy, see pixi.toml
+      run: pixi run test || true
+    - name: Prepare for downstream tests
+      run: pixi run install-flatsurf-suite-dependencies
+    - name: Run cppyythonizations test suite
+      run: pixi run test-cppyythonizations
+      continue-on-error: true
+    - name: Install cppyythonizations for later tests
+      run: pixi run install-cppyythonizations
+    - name: Run gmpxxyy test suite
+      run: pixi run test-gmpxxyy
+      continue-on-error: true
+    - name: Install gmpxxyy for later tests
+      run: pixi run install-gmpxxyy
+    - name: Run e-antic test suite
+      run: pixi run test-e-antic
+      continue-on-error: true
+    - name: Install e-antic for later tests
+      run: pixi run install-e-antic
+    - name: Run exact-real test suite
+      run: pixi run test-exact-real
+      continue-on-error: true
+    - name: Install exact-real for later tests
+      run: pixi run install-exact-real
+    - name: Run intervalxt test suite
+      run: pixi run test-intervalxt
+      continue-on-error: true
+    - name: Install intervalxt for later tests
+      run: pixi run install-intervalxt
+    - name: Run flatsurf test suite
+      run: pixi run test-flatsurf
+      continue-on-error: true
+    - name: Install flatsurf for later tests
+      run: pixi run install-flatsurf
+    - name: Run sage-flatsurf test suite
+      run: pixi run test-sage-flatsurf
+      continue-on-error: true
